### ISSUE TITLE
[Android Bootcamp]- Project 0: Todo -Ready for Review

### ISSUE THREAD

**Issue by nidhisaini** [nidhisaini/codepath-android-Todo#2]
My app is complete, please review. /cc @codepathreview @codepath

In addition, I have a question about background color of an activity. I have added the background like this:
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
   .....
    android:background="@color/backcolor">
Is this the correct approach?

**Comment by nesquena** [comment]
Nidhi,

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer  learn the practical elements of Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to **schedule a short 10 minute phone conversation** with us. Navigate to [today's date and onward from there](https://calendar.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU) and choose an available 15-minute slot in the mornings or evenings. Let us know if none of those times work.

With regards to extensions to implement, we are looking for developers with an interest in user experience and product development so be sure to focus on additional functional enhancements and/or improving the user interface of the app.

Once you select a slot, can you make sure to **include the best number** to reach you at to the invite?

**Prior to our chat**, can you take some time to research the most common Android Activity lifecycle methods as well as the `ArrayAdapter` pattern used when working with lists? We will be discussing these topics with you conceptually in the phone call. We encourage you to [search our guides](http://guides.codepath.com/android/) as well as any other sources you'd like.

Look forward to chatting soon!

**Comment by nesquena** [comment]
> In addition, I have a question about background color of an activity. 

Yep definitely, what you did changing the background property is a reasonable way to achieve that!

**Comment by nidhisaini** [comment]
Thanks for reviewing the project.

**Comment by nidhisaini** [comment]
![tododemo1](https://cloud.githubusercontent.com/assets/5497374/16430989/31080ec4-3d33-11e6-96f2-fff90a2eafcd.gif)

**Comment by nesquena** [comment]
Great to see you were able to augment your app with a multiple extension tasks now! As mentioned earlier, the extension tasks available on each project are often the most valuable learnings since they dive deeper into common real-world Android use cases.

We'll be in touch with you again soon via email. Let me know if you have any questions about the project or anything in the meantime.
